### ISSUE TITLE
Registration Not Working

### ISSUE THREAD

**Issue by polarisfm** [nickolas360/harmony#8]
It appears that registration isn't working with harmony.
Error encountered while running the command:

```
Error encountered while running the command:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/harmony.py", line 245, in exec_single_command
    func()
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/harmony.py", line 163, in result
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/harmony.py", line 375, in register
    username=username, password=password)
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/harmony.py", line 287, in try_with_captcha
    response, exception = self.try_request(func, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/harmony.py", line 315, in try_request
    return func(*args, **kwargs), None
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/discord.py", line 451, in register
    "fingerprint": self.get_or_request_fingerprint(),
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/discord.py", line 416, in get_or_request_fingerprint
    self.request_fingerprint()
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/discord.py", line 411, in request_fingerprint
    }, allow_errors=None, referer="login?redirect=%2F")
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/discord.py", line 385, in get
    return self.http_request(requests.get, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/harmony_discord-0.5.2.dev0-py3.5.egg/harmony/discord.py", line 349, in http_request
    r = func(get_full_url(url), headers=headers, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

```
This happens after I reenter the password.
I'm not sure why this is. I did notice a new part of the Discord API called "science" which isn't implimented. I'm not sure if that's related or not, though, as I've not had time to poke around with it more.

**Comment by nickolas360** [comment]
I believe I've fixed this issue in version 0.6.0—I was able to register successfully. Unfortunately, issues with reCAPTCHA are often making it impossible to test. Please see [this issue for librecaptcha](https://github.com/nickolas360/librecaptcha/issues/7).
